<?php

?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <?=$welcome?>
    <h1>List of routes</h1>
    <ul>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/dbtest">Database test</a></li>
        <ul>
            <li><a href="/fixedTypeArrayTest">FixedTypeArray test</a></li>
            <li><a href="/fixedLengthArrayTest">FixedLengthArray test</a></li>
        </ul>
        <li><a href="/redirectTest">Redirect test</a></li>
    </ul>
</body>
</html>