<?php
    $require = require('app/header.gravity.phtml');
?>


    <h1>List of routes</h1>
    <ul>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/dbtest">Database test</a></li>
        <ul>
            <li><a href="/fixedTypeArrayTest">FixedTypeArray test</a></li>
            <li><a href="/fixedLengthArrayTest">FixedLengthArray test</a></li>
        </ul>
        <li><a href="/redirectTest">Redirect test</a></li>
    </ul>
</body>
</html>