<?php
    $require = require('app/header.gravity.phtml');
?>


    <h1>Backend utilities</h1>
    <ul>
        <li><a href="/about">About</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/dbtest">Database test</a></li>
        <li>Data Types</li>
        <ul>
            <li><a href="/fixedTypeArrayTest">FixedTypeArray test</a></li>
            <li><a href="/fixedLengthArrayTest">FixedLengthArray test</a></li>
        </ul>
        <li><a href="/redirectTest">Redirect test</a></li>
        <li>Dynamic get parameters</li>
        <ul>
            <li><a href="/urlparams/key/5">Dynamic url params</a></li>
            <li><a href="/version/stable/1.x">Dynamic url params 2</a></li>
            <li><a href="/urlparams/key/asd/asdasd/2">Dynamic url params 3</a></li>
            <li><a href="/hello/1">Dynamic url params 4</a></li>
        </ul>
        <li>
            <a href="/formattingString">Formatting string test</a>
        </li>
    </ul>
    <h1>Frontend utilities</h1>
    <ul>
        <li><a href="/front-showcase/get-data">Getting data from</a></li>
    </ul>
</body>
</html>

<?php
    $require = require('app/footer.gravity.phtml');
?>